resources:
  jobs:
    endpoint_deployment_job:
      name: 5-1-endpoint-deployment
      tags:
        project_name: "brickkit"

      environments:
        - environment_key: default
          spec:
            environment_version: "4"
            dependencies:
              - ../dist/*.whl

      tasks:
        - task_key: run_notebook
          environment_key: default
          notebook_task:
            notebook_path: ../notebooks/5.1_endpoint_deployment.py
            base_parameters:
              env: ${bundle.target}
              git_sha: "${var.git_sha}"
              run_id: "{{job.run_id}}"
